<?php
/**
 * Created by PhpStorm.
 * User: xterminate
 * Date: 10.03.2019
 * Time: 15:13
 */

namespace Classes;


class MRSocial extends Social
{
    public function generateAuthUrl()
    {
        parent::generateAuthUrl(); // TODO: Change the autogenerated stub
        $params = [
            'client_id' => $this->getClientId(),
            'redirect_uri' => $this->getRedirectUri(),
            'response_type' => $this->getResponseType()
        ];
        return $this->url . '?' . urldecode(http_build_query($params));
    }

}