<?php
/**
 * Created by PhpStorm.
 * User: xterminate
 * Date: 10.03.2019
 * Time: 15:13
 */

namespace Classes;


use function curl_init;

class OKSocial extends Social
{
    public function generateAuthUrl()
    {
        parent::generateAuthUrl();
        $params = [
            'client_id' => $this->getClientId(),
            'redirect_uri' => $this->getRedirectUri(),
            'response_type' => $this->getResponseType()
        ];
        return $this->url . '?' . urldecode(http_build_query($params));
    }

    public function authorize($code)
    {
        parent::authorize($code);

        $this->setCode($code);

        // Generate token post fields
        $tokenPostFields = $this->generateTokenPostFields();
        $url = 'http://api.odnoklassniki.ru/oauth/token.do';

        // Retrieve token from oauth server
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $tokenPostFields); // передаём параметры
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        $result = curl_exec($curl);
        curl_close($curl);
        $token = json_decode($result, true);

        // Get user info using token
        return $this->getUserInfo($token);
    }

    public function generateTokenPostFields()
    {
        parent::generateTokenPostFields();
        $tokenParams = [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'code' => $this->code,
            'redirect_uri' => $this->redirectUri,
            'grant_type' => $this->grantType
        ];
        return urldecode(http_build_query($tokenParams));
    }

    public function getUserInfo($token)
    {
        parent::getUserInfo($token); // TODO: Change the autogenerated stub
        $userInfo = false;

        if (isset($token['access_token'])) {
            $params = [
                'method' => 'users.getCurrentUser',
                'access_token' => $token['access_token'],
                'application_key' => $this->publicKey,
                'format' => 'json',
                'fields' => 'PIC128X128,FIRST_NAME,LAST_NAME'
            ];

            $sign = md5("application_key=" .
                $this->publicKey . "fields=" . $params['fields'] .
                "format=jsonmethod=users.getCurrentUser" .
                md5("{$token['access_token']}" . $this->clientSecret));

            $params['sig'] = $sign;

            $res = json_decode(file_get_contents('http://api.odnoklassniki.ru/fb.do' . '?' . urldecode(http_build_query($params))), true);

            if (isset($res['uid'])) {
                $userInfo = $res;
                $userInfo = [
                    'external_id' => $userInfo['uid'],
                    'first_name' => $userInfo['first_name'],
                    'last_name' => $userInfo['last_name'],
                    'avatar' => $userInfo['pic128x128']
                ];
            }
        }

        return $userInfo;
    }

}