<?php
/**
 * Created by PhpStorm.
 * User: xterminate
 * Date: 10.03.2019
 * Time: 15:13
 */

namespace Classes;


class VKSocial extends Social
{
    public function generateAuthUrl()
    {
        parent::generateAuthUrl(); // TODO: Change the autogenerated stub
        $params = [
            'client_id' => $this->getClientId(),
            'redirect_uri' => $this->getRedirectUri(),
            'response_type' => $this->getResponseType()
        ];
        $authUrl = $this->url . '?' . urldecode(http_build_query($params));
        return $authUrl;
    }

    public function authorize($code)
    {
        parent::authorize($code); // TODO: Change the autogenerated stub

        $this->setCode($code);

        // Generate token url
        $tokenUrl = $this->generateTokenUrl();

        // Retrieve token from oauth server
        $token = json_decode(file_get_contents($tokenUrl), true);

        // Get user info using token
        return $this->getUserInfo($token);
    }

    public function generateTokenUrl()
    {
        parent::generateTokenUrl();
        $tokenParams = [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'code' => $this->code,
            'redirect_uri' => $this->redirectUri
        ];
        return 'https://oauth.vk.com/access_token' . '?' .
            urldecode(http_build_query($tokenParams));
    }

    public function getUserInfo($token)
    {
        parent::getUserInfo($token); // TODO: Change the autogenerated stub
        $userInfo = false;

        if (isset($token['access_token'])) {
            $params = array(
                'uids' => $token['user_id'],
                'fields' => 'uid,first_name,last_name,screen_name,sex,bdate,photo_100',
                'access_token' => $token['access_token'],
                'v' => '5.21'
            );

            $res = json_decode(file_get_contents('https://api.vk.com/method/users.get' . '?' .
                urldecode(http_build_query($params))), true);

            if (isset($res['response'][0]['id'])) {
                $userInfo = $res['response'][0];
                $userInfo = [
                    'external_id' => $userInfo['id'],
                    'first_name' => $userInfo['first_name'],
                    'last_name' => $userInfo['last_name'],
                    'screen_name' => $userInfo['screen_name'],
                    'avatar' => $userInfo['photo_100'],
                    'b_date' => $userInfo['bdate']
                ];
            }
        }
        return $userInfo;
    }

}
