<?php
/**
 * Created by PhpStorm.
 * User: xterminate
 * Date: 10.03.2019
 * Time: 15:13
 */

namespace Classes;


class YXSocial extends Social
{
    public function generateAuthUrl()
    {
        parent::generateAuthUrl(); // TODO: Change the autogenerated stub
        $params = [
            'client_id' => $this->getClientId(),
            'redirect_uri' => $this->getRedirectUri(),
            'response_type' => $this->getResponseType(),
            'display' => 'popup'
        ];
        return $this->url . '?' . urldecode(http_build_query($params));
    }

    public function authorize($code)
    {
        parent::authorize($code);

        $this->setCode($code);

        // Generate token post fields
        $tokenPostFields = $this->generateTokenPostFields();
        $url = 'https://oauth.yandex.ru/token';

        // Retrieve token from oauth server
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $tokenPostFields); // передаём параметры
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        $result = curl_exec($curl);
        curl_close($curl);
        $token = json_decode($result, true);

        // Get user info using token
        return $this->getUserInfo($token);
    }

    public function generateTokenPostFields()
    {
        parent::generateTokenPostFields();
        $tokenParams = [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'code' => $this->code,
            'redirect_uri' => $this->redirectUri,
            'grant_type' => $this->grantType

        ];
        return urldecode(http_build_query($tokenParams));
    }

    public function getUserInfo($token)
    {
        parent::getUserInfo($token);
        $userInfo = false;

        if (isset($token['access_token'])) {
            $params = [
                'format' => 'json',
                'oauth_token'  => $token['access_token']
            ];

            $res = json_decode(file_get_contents('https://login.yandex.ru/info' . '?' . urldecode(http_build_query($params))), true);

            if (isset($res['id'])) {
                $userInfo = $res;
                $userInfo = [
                    'external_id' => $userInfo['id'],
                    'first_name' => $userInfo['first_name'],
                    'last_name' => $userInfo['last_name'],
                    'avatar' => 'https://avatars.yandex.net/get-yapic/'.$userInfo['default_avatar_id'].'/islands-200'
                ];
            }
        }

        return $userInfo;
    }
}